### ISSUE TITLE
Dose not work pattern and orderr in Foxy Proxy Standart 7.0

### ISSUE THREAD

**Issue by khenarghot** [foxyproxy/firefox-extension#28]
Firefox 68.0.2 (Fedora 29)

The paterrn matching dose not work in any order of proxis.

**Comment by ericjung** [comment]
Can you please export your settings and paste here? Otherwise give an example I can test. Thank you

**Comment by Monsterovich** [comment]
>The paterrn matching dose not work in any order of proxis.

I have this problem too. I just rolled back to the older version.

**Comment by ericjung** [comment]
This is fixed in version 7.1. It is submitted to Mozilla. They must approve it; then it will be automatically released. I am very sorry! Did many hours of testing, including multiple proxies and multiple patterns, but looks like I missed multiple white & black patterns on a single proxy in final testing (but did do it in earlier testing). The specific bug was this:

https://github.com/foxyproxy/firefox-extension/commit/b5e1a06f77c5250da0584285320713f69f30bb06#diff-e17479ef6e327667196492b935d04068

missing parens on line 52 and 59.

**Comment by hydrandt** [comment]
Thanks Eric for fixing so quickly! I was just about to write a bugreport :-) Good that github suggests also closed issues while composing an issue title.

**Comment by ericjung** [comment]
7.1 is available now. To force Firefox to get it:

1. go to the firefox addons page in your browser (or just type about:addons in the address bar)
2. click gear icon then "Check for Updates"

**Comment by valepu** [comment]
Hi,
I have version 7.1 (in the info page it says  Version: 7.1) but Pattern and order is still not working.
The normal proxy wasn't working either until i disabled and re-enabled the extension

**Comment by ericjung** [comment]
@valepu  please update to 7.2 and reopen this bug if the problem persists. 7.2 addresses this bug specifically.

to update:

go to the firefox addons page in your browser (or just type about:addons in the address bar)
click gear icon then "Check for Updates"

**Comment by valepu** [comment]
Thanks, it works now
